In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pickle
import gzip
import tensorflow as tf
import glob
import math
import skimage

In [2]:
common_dir = '/home/justinvyu/ray_results'
universe = 'gym'
domain = 'Point2D'
task = 'Maze-v0'

In [3]:
base_path = os.path.join(common_dir, universe, domain, task)
exps = sorted(list(glob.iglob(os.path.join(base_path, '*'))))
for i, exp in enumerate(exps):
    print(f'{i} \t {exp.replace(base_path, "")}')
    
exp_choice = int(input('\n Which experiment do you want to analyze? (ENTER A NUMBER) \t'))

exp_path = exps[exp_choice]
print('\n')
seeds = sorted(list(glob.iglob(os.path.join(exp_path, '*'))))
seeds = [seed for seed in seeds if os.path.isdir(seed)]
for i, seed in enumerate(seeds):
    print(f'{i} \t {seed.replace(exp_path, "")}')
    
# TODO: Extend to analyzing all seeds
seed_choice = int(input('\n Which seed do you want to analyze? (ENTER A NUMBER) \t'))

seed_path = seeds[seed_choice]

print('PATH:\n', seed_path)

0 	 /2020-03-20T01-13-01-vice_easymaze_singlreset_mixup
1 	 /2020-03-20T01-15-53-vice_mediummaze_singlreset_mixup
2 	 /2020-03-20T01-26-41-vice_hardmaze_singlreset_mixup
3 	 /2020-03-20T01-28-50-sqil_easymaze
4 	 /2020-03-20T01-35-22-vice_mediummaze_singlreset_mixup_100pathlength
5 	 /2020-03-25T21-35-26-ddl_fixedreset_fixedgoaldist_easymaze
6 	 /2020-03-27T11-53-22-ddl_fixedreset_easymaze_exactgoalrerun
7 	 /2020-03-27T11-54-05-ddl_fixedreset_mediummaze
8 	 /2020-03-27T11-59-43-ddl_fixedreset_hardmaze
9 	 /2020-04-06T23-10-00-herqlearning_everytransition_easymaze
10 	 /2020-04-07T00-17-37-herqlearning_everytransition_easymaze_keepsparserew
11 	 /2020-04-09T12-45-03-sac_sparse_easymaze_discretizedcountexplore
12 	 /2020-04-09T14-15-06-vice_easymaze_discretizedcountexplore
13 	 /2020-04-09T14-31-29-sac_sparse_mediummaze_discretizedcountexplore
14 	 /2020-04-09T16-35-34-sac_sparse_mediummaze_discretizedcountexplore_rerun
15 	 /2020-04-09T16-54-58-vice_easymaze_discretizedcountexplore
16 

In [4]:
checkpoint_dir = os.path.join(seed_path, 'checkpoint_100')
with open(os.path.join(checkpoint_dir, 'checkpoint.pkl'), 'rb') as f:
    checkpoint = pickle.load(f)

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html


W0504 15:37:33.228536 139918765803328 deprecation.py:506] From /home/justinvyu/anaconda3/envs/softlearning/lib/python3.7/site-packages/tensorflow_core/python/ops/init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0504 15:37:33.229941 139918765803328 deprecation.py:506] From /home/justinvyu/anaconda3/envs/softlearning/lib/python3.7/site-packages/tensorflow_core/python/ops/init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0504 15:37:33.247099 139918765803328 deprecation.py:506] From /home/justinvyu/anaconda3/envs/softlearning/lib/python3.7/site-packages/tensorflow_

In [9]:
replay_pool_path = os.path.join(checkpoint_dir, 'replay_pool.pkl')

from softlearning.replay_pools.utils import get_replay_pool_from_variant
variant = checkpoint['variant']
training_environment = checkpoint['training_environment']
replay_pool = get_replay_pool_from_variant(variant, training_environment)

replay_pool.load_experience(replay_pool_path)

In [13]:
replay_pool.data[('episode_index_forwards', )][:100]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],

In [23]:
print(replay_pool.size)
replay_pool.data[replay_pool.random_indices(10)]

10000


TypeError: unhashable type: 'numpy.ndarray'

In [22]:
variant

{'git_sha': '3621f35be79be884cf112e4502d5714e8680ffce justin-changes',
 'environment_params': {'training': {'domain': 'Point2D',
   'task': 'Fixed-v0',
   'universe': 'gym',
   'kwargs': {'ball_radius': 0.5,
    'target_radius': 0.5,
    'boundary_distance': 4,
    'images_are_rgb': True,
    'init_pos_range': None,
    'target_pos_range': None,
    'render_onscreen': False,
    'reward_type': 'dense',
    'observation_keys': ('state_observation', 'state_desired_goal')}},
  'evaluation': {'domain': 'Point2D',
   'task': 'Fixed-v0',
   'universe': 'gym',
   'kwargs': {'ball_radius': 0.5,
    'target_radius': 0.5,
    'boundary_distance': 4,
    'images_are_rgb': True,
    'init_pos_range': None,
    'target_pos_range': None,
    'render_onscreen': False,
    'reward_type': 'dense',
    'observation_keys': ('state_observation', 'state_desired_goal')}}},
 'policy_params': {'type': 'GaussianPolicy',
  'kwargs': {'hidden_layer_sizes': (512, 512),
   'squash': True,
   'observation_keys': No

In [7]:
embedding = checkpoint['distance_estimator']

In [8]:
embedding.summary()

Model: "embedding_fn"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
state_observation (InputLaye [(None, 2)]               0         
_________________________________________________________________
feedforward_embedding_fn (Pi (None, 2)                 67074     
Total params: 67,074
Trainable params: 67,074
Non-trainable params: 0
_________________________________________________________________


In [9]:
test = tf.ones((10, 2))

In [15]:
sess = tf.keras.backend.get_session()
sess.run(embedding(test))

array([[-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822]], dtype=float32)

In [14]:
embedding.predict(np.ones((10, 2)))

array([[-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822],
       [-1.3965508,  1.2660822]], dtype=float32)